FROM microsoft/aspnetcore-build

# All this for mono. Thanks a lot, CAKE...
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/debian jessie main" | tee /etc/apt/sources.list.d/mono-official.list
RUN apt-get update
RUN apt install mono-complete -y

WORKDIR /app
EXPOSE 3000
COPY ./api-init-dev-env.sh /app
COPY ./build.sh /app
COPY ./development.env /app
RUN chmod +x ./api-init-dev-env.sh
RUN chmod +x ./build.sh
ENTRYPOINT ["./api-init-dev-env.sh"]
