FROM microsoft/aspnetcore-build

# All this for mono. Thanks a lot, CAKE...
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/debian jessie main" | tee /etc/apt/sources.list.d/mono-official.list
RUN apt-get update
RUN apt install mono-complete -y

# NPM Behave
RUN node --max_old_space_size=256 $(which npm) install
RUN npm config set jobs 1
RUN npm install --max-old-space-size=300

WORKDIR /app
EXPOSE 5000
COPY ./web-init-dev-env.sh /app
COPY ./development.env /app
RUN chmod +x ./web-init-dev-env.sh
ENTRYPOINT ["./web-init-dev-env.sh"]
