FROM alpine
RUN apk add --no-cache bash gawk sed grep bc coreutils curl python python-dev py-pip
RUN curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
RUN chmod +x /usr/local/bin/ecs-cli
RUN ecs-cli --version
RUN pip install awscli
COPY docker-compose.prod.yml .
